name: "Update APT repo"
description: "Update APT repo on GitHub pages with new packages."
inputs:
  debug:
    description: "Print debug log"
    required: false
  github_token:
    description: "GitHub token with commit and push scope."
    required: true
  git_commit_message:
    description: "Git commit message."
    required: false
    default: "[apt-action] Update apt repo with last pushed updates."
  git_push_branch:
    description: "Git branch to push to."
    required: false
    default: "master"
  repo_supported_arch:
    description: "Newline-delimited list of supported architectures."
    required: true
  repo_supported_distro:
    description: "Newline-delimited list of supported distributions."
    required: true
  repo_directory:
    description: "Location of APT repo folder relative to git repo root."
    required: false
    default: "apt"
  update_directory:
    description: "Directory in which updated packages are placed."
    required: false
    default: "updates"
  private_key:
    description: "GPG private key for signing apt repo"
    required: true
  key_passphrase:
    description: "Passphrase of GPG private key"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "upload-cloud"
  color: "blue"
